# Generated by Django 4.0 on 2023-09-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ParameterType',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enabled', models.BooleanField()),
                ('ValidityStartDate', models.DateTimeField()),
                ('ValidityEndDate', models.DateTimeField()),
                ('FilterField1', models.TextField(blank=True, null=True)),
                ('FilterField2', models.TextField(blank=True, null=True)),
                ('FilterField3', models.TextField(blank=True, null=True)),
                ('Value', models.TextField(blank=True, null=True)),
                ('ParameterTypeId', models.ForeignKey(db_column='ParameterTypeId', on_delete=django.db.models.deletion.CASCADE, to='parameters.parametertype')),
            ],
            options={
                'db_table': 'Parameter',
            },
        ),
    ]
