# Generated by Django 4.0 on 2023-09-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='Value',
            field=models.TextField(default='algo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametertype',
            name='Description',
            field=models.TextField(),
        ),
    ]
