# Generated by Django 4.0 on 2023-09-11 18:20

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_alter_parameter_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='Enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='ValidityEndDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 18, 20, 20, 827822, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='ValidityStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
