# Generated by Django 4.0 on 2023-11-10 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_alter_parameter_filterfield1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ValidityEndDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 15, 18, 42, 873234, tzinfo=utc)),
        ),
    ]
