# Generated by Django 4.0 on 2023-11-07 16:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_alter_parameter_filterfield1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ValidityEndDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 16, 40, 32, 721044, tzinfo=utc)),
        ),
    ]
