# Usar una imagen base oficial de Python
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo .env al contenedor
COPY .env /app/

# [Aquí puedes agregar más comandos según tus necesidades]

# Comando para mantener el contenedor en ejecución (este puede variar según tus necesidades)
CMD ["tail", "-f", "/dev/null"]

