# Usar una imagen base oficial de Python
FROM python:3.10

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Instalar dependencias del sistema para Oracle
RUN apt-get update \
    && apt-get install -y --no-install-recommends libaio1 wget unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Descargar e instalar el cliente instantáneo de Oracle
RUN wget https://download.oracle.com/otn_software/linux/instantclient/2111000/instantclient-basic-linux.x64-21.11.0.0.0dbru.zip \
    && unzip instantclient-basic-linux.x64-21.11.0.0.0dbru.zip -d /opt/oracle \
    && rm instantclient-basic-linux.x64-21.11.0.0.0dbru.zip \
    && sh -c "echo /opt/oracle/instantclient_21_11 > /etc/ld.so.conf.d/oracle-instantclient.conf" \
    && ldconfig

# Instalar dependencias de Python
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el proyecto
COPY . /app/

# Comando para ejecutar la aplicación
CMD ["gunicorn", "-b", "0.0.0.0:8000", "integraSoft_rest.wsgi:application"]


