# Generated by Django 4.0 on 2023-11-10 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='users.user'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
